version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: octofit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: octofit-backend
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/octofit_db
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: octofit-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  mongo-data:
