apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitlearn-backend
  labels:
    app: fitlearn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fitlearn
  template:
    metadata:
      labels:
        app: fitlearn
    spec:
      containers:
        - name: backend
          image: fitlearn-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mongodb://mongo:27017/fitlearn"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fitlearn-secret
                  key: secret_key
            - name: DEBUG
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: fitlearn-backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: fitlearn